exports.handler = async (event, context) => {
  if (event.httpMethod !== "POST") {
    return {
      statusCode: 405,
      body: JSON.stringify({ error: "Method Not Allowed" }),
    };
  }

  try {
    const { messages, categoryPrompt } = JSON.parse(event.body || "{}");
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey || apiKey.trim() === "" || apiKey === "MY_GEMINI_API_KEY") {
      return {
        statusCode: 400,
        body: JSON.stringify({
          error: "GEMINI_API_KEY environment variable is missing or invalid on Netlify. Please check Site configuration > Environment variables.",
        }),
      };
    }

    let systemInstructionText = `You are Eco Buddy, an enthusiastic, knowledgeable, and encouraging AI sustainability assistant. Provide practical eco-friendly tips, water-saving advice, energy reduction strategies, recycling guidance, and sustainable transport advice.`;
    if (categoryPrompt) {
      systemInstructionText += ` Focus area: ${categoryPrompt}`;
    }

    const contents = (messages || []).map((m) => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.content }],
    }));

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey.trim()}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          systemInstruction: {
            parts: [{ text: systemInstructionText }],
          },
          contents: contents,
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 1000,
          },
        }),
      }
    );

    const data = await response.json();

    if (!response.ok) {
      const errMsg = data?.error?.message || `Gemini API returned status ${response.status}`;
      return {
        statusCode: response.status,
        body: JSON.stringify({ error: errMsg }),
      };
    }

    const replyText =
      data?.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by Gemini.";

    return {
      statusCode: 200,
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ reply: replyText }),
    };
  } catch (error) {
    return {
      statusCode: 500,
      body: JSON.stringify({ error: error.message || "Server Internal Error" }),
    };
  }
};


